; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = lvgl_demo
boards_dir = ./board
description = Gravimetric Shots - BLE Espresso Scale Controller

[env]
platform = espressif32
board = T-Display-Long
framework = arduino
board_build.partitions = huge_app.csv

[env:lvgl_demo]
extends = env
; Standard libraries from Git, custom AcaiaArduinoBLE and UI in lib/
lib_deps =
    https://github.com/arduino-libraries/ArduinoBLE.git#1.4.1
    https://github.com/lvgl/lvgl.git#v8.3.0
build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -I lib
